[YZ] add scripts and configure with tar ball

diff --git a/cassandra b/cassandra
--- a/cassandra
+++ b/cassandra
@@ -16,6 +16,7 @@ export CASSANDRA_OWNR=cassandra
 NAME="cassandra"
 log_file=/var/log/cassandra/cassandra.log
 pid_file=/var/run/cassandra/cassandra.pid
+lock_file=/var/lock/subsys/$NAME
 CASSANDRA_PROG=/usr/sbin/cassandra
 
 # The first existing directory is used for JAVA_HOME if needed.
@@ -45,32 +46,39 @@ if [ -z "$JAVA_HOME" ]; then
         # if JAVA_HOME is still empty here, punt.
     fi
 fi
-JAVA="$JAVA_HOME/bin/java"
-export JAVA_HOME JAVA
-
 # add by yan for debug
-export JAVA_HOME=/opt/cscloud/jdk1.7.0_25
-export JAVA=/opt/cscloud/jdk1.7.0_25/bin/java
-echo $JAVA_HOME
-echo $JAVA
+#JAVA="$JAVA_HOME/bin/java"
+#export JAVA_HOME JAVA
+export JAVA_HOME=/opt/cscloud/jdk-latest
+export JAVA=/opt/cscloud/jdk-latest/bin/java
 
 case "$1" in
     start)
         # Cassandra startup
         echo -n "Starting Cassandra: "
         su $CASSANDRA_OWNR -c "$CASSANDRA_PROG -p $pid_file" > $log_file 2>&1
+        retval=$?
+        [ $retval -eq 0 ] && touch $lock_file
         echo "OK"
         ;;
     stop)
         # Cassandra shutdown
         echo -n "Shutdown Cassandra: "
         su $CASSANDRA_OWNR -c "kill `cat $pid_file`"
+        retval=$?
+        [ $retval -eq 0 ] && rm -f $lock_file
         for t in `seq 40`; do $0 status > /dev/null 2>&1 && sleep 0.5 || break; done
         # Adding a sleep here to give jmx time to wind down (CASSANDRA-4483). Not ideal...
         # Adam Holmberg suggests this, but that would break if the jmx port is changed
         # for t in `seq 40`; do netstat -tnlp | grep "0.0.0.0:7199" > /dev/null 2>&1 && sleep 0.1 || break; done
         sleep 5
-        echo "OK"
+        STATUS=`$0 status`
+        if [[ $STATUS == "$NAME is stopped" ]]; then
+            echo "OK"
+        else
+            echo "ERROR: could not stop $NAME:  $STATUS"
+            exit 1
+        fi
         ;;
     reload|restart)
         $0 stop
